version: "3.8"
services:
  backend:
    build: ./backend/
    ports:
      - 5000:5000
    networks:
      - postgres
    depends_on:
      - postgres
  postgres:
    build: ./db/
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge