"""added book reviews

Revision ID: 2be7c9831642
Revises: bcdf06a2e368
Create Date: 2023-10-10 12:12:18.257100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be7c9831642'
down_revision: Union[str, None] = 'bcdf06a2e368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('book_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('reviews', 'book_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_type', sa.VARCHAR(), nullable=False))
    op.drop_table('book_reviews')
    # ### end Alembic commands ###
