"""removed column

Revision ID: 7f239d263d6c
Revises: 2be7c9831642
Create Date: 2023-10-10 12:19:03.033188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f239d263d6c'
down_revision: Union[str, None] = '2be7c9831642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_type', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
